import { headers } from "next/headers";
import { SideNavBar } from "@/components/side-nav-bar/side-nav-bar";
import { getTitleFromPath } from "./utils/getTitleFromPath";

import styles from './styles.module.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const reqHeaders = headers();
  const path = reqHeaders.get('x-invoke-path');
  return (
    <html lang="en">
      <body className={styles.body}>
        <SideNavBar />
        <div className={styles.contentBox}>
          <div className={styles.titleBox}>
            {getTitleFromPath(path)}
          </div>
          <div className={styles.bodyBox}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
